# Generated by Django 3.2.14 on 2022-07-24 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.PositiveSmallIntegerField(choices=[(4, 'Memoir and Autobiography'), (2, 'Nonfiction'), (1, 'Mystery and Thriller'), (7, 'Fiction'), (0, 'Fantasy'), (6, 'Romance'), (5, 'Novel'), (3, 'Horror')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='cover')),
                ('average_rating', models.FloatField(null=True)),
                ('thumbnail', models.URLField(null=True)),
                ('authors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='random_tbr.author')),
                ('categories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='random_tbr.category')),
            ],
        ),
    ]
